font_family UDEV Gothic 35NFLG
bold_font UDEV Gothic 35NFLG Bold
italic_font UDEV Gothic 35NFLG Italic
bold_italic_font UDEV Gothic 35NFLG Bold Italic

font_size 14.0
adjust_line_height 0

map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+] set_background_opacity +0.05
map ctrl+[ set_background_opacity -0.05
map ctrl+shift+] set_background_opacity 1
map ctrl+shift+[ set_background_opacity 0.70

cursor_blink_interval 0.5
cursor_stop_blinking_after 0

window_padding_width 4
hide_window_decorations yes
remember_window_size no
initial_window_width 50c
initial_window_height 32c
initial_window_x 445
initial_window_y 58

background_opacity 0.70
dynamic_background_opacity yes
enable_audio_bell no

cursor_shape block
shell_integration enabled

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
