alias php74='C:/xampp/php74/php.exe'
alias php7='C:/xampp/php74/php.exe'
alias php8='C:/xampp/php/php.exe'
alias php81='C:/xampp/php/php.exe'
alias nvim='"C:/Program Files/Neovim/bin/nvim.exe"'
alias nv='nvim'
alias setphp="~/.dotfiles/setphp.sh"
alias php="$(setphp)"
alias artisan="php artisan"
alias art="artisan"
