#!/usr/bin/env bash

### makes that the script fails if a step fails
set -e

###############################################################################
# Clone dotfiles
###############################################################################

read -rep $'\nWhere do you want to clone these dotfiles to [~/.dotfiles]? ' clone_path
clone_path="${clone_path:-"${HOME}/.dotfiles"}"

# Ensure path doesn't exist.
while [ -e "${clone_path}" ]; do
    read -rep $'\nPath exists, try again? (y) ' y
    case "${y}" in
        [Yy]*)

            break;;
        *) echo "Please answer y or CTRL+c the script to abort everything";;
    esac
done

echo

# This is used to locally develop the install script.
git clone https://github.com/Pietietjie/.dotfiles "${clone_path}"

cd ${clone_path}

os_type="$(uname -s)"

git submodule init && git submodule update

git remote remove origin && git remote add origin git@github.com:Pietietjie/.dotfiles.git
git branch --set-upstream-to=origin/main main

###############################################################################
# Detect OS and distro type
###############################################################################

case "${os_type}" in
    Linux*)
        os_type="Linux"

        if [   -f "/etc/debian_version" ]; then
            sudo ./install || true
            sudo ./install -c ./install-ubuntu.conf.yaml -p dotbot-aptget/aptget.py || true
        fi

        ./install || true

        ;;
esac

cat << EOF
Everything was installed successfully!

You can safely close this terminal.
EOF

exit 0
