include "/run/current-system/sw/share/X11/locale/en_US.UTF-8/Compose"

<Multi_key> <equal> <e> : "€" U20AC
<Multi_key> <minus> <minus> <minus> : "—" U2014
<Multi_key> <minus> <minus> : "–" U2013
<Multi_key> <o> <c> : "©" U00A9
<Multi_key> <o> <r> : "®" U00AE
<Multi_key> <o> <c> : "©" U00A9

<Multi_key> <asciicircum> <e> : "ê" U00EA
<Multi_key> <asciicircum> <E> : "Ê" U00CA
<Multi_key> <asciicircum> <a> : "â" U00E2
<Multi_key> <asciicircum> <A> : "Â" U00C2
<Multi_key> <asciicircum> <o> : "ô" U00F4
<Multi_key> <asciicircum> <O> : "Ô" U00D4
<Multi_key> <asciicircum> <u> : "û" U00FB
<Multi_key> <asciicircum> <U> : "Û" U00DB
<Multi_key> <asciicircum> <i> : "î" U00EE
<Multi_key> <asciicircum> <I> : "Î" U00CE

<Multi_key> <apostrophe> <e> : "é" U00E9
<Multi_key> <apostrophe> <E> : "É" U00C9
<Multi_key> <grave> <e> : "è" U00E8
<Multi_key> <grave> <E> : "È" U00C8

<Multi_key> <asciitilde> <n> : "ñ" U00F1
<Multi_key> <asciitilde> <N> : "Ñ" U00D1
<Multi_key> <dead_diaeresis> <e> : "ë" U00EB
<Multi_key> <dead_diaeresis> <E> : "Ë" U00CB
